// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdtCATtecvZcekgDK1CqCAGRzSNdTZvB0',
    appId: '1:73695287611:web:fd46d4fac847bf7ebfbf1e',
    messagingSenderId: '73695287611',
    projectId: 'mini-app-8f189',
    authDomain: 'mini-app-8f189.firebaseapp.com',
    databaseURL: 'https://mini-app-8f189-default-rtdb.firebaseio.com',
    storageBucket: 'mini-app-8f189.appspot.com',
    measurementId: 'G-TB6PJDMSJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Hzox40xrIPLurJC1vHiCvaa_V9mHTnM',
    appId: '1:73695287611:android:3a9dc26d7d1f14d8bfbf1e',
    messagingSenderId: '73695287611',
    projectId: 'mini-app-8f189',
    databaseURL: 'https://mini-app-8f189-default-rtdb.firebaseio.com',
    storageBucket: 'mini-app-8f189.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9OuRSY4bz99wI4k9MGwXKv8wWPRbFWZ0',
    appId: '1:73695287611:ios:1c6ef0d67de8ed18bfbf1e',
    messagingSenderId: '73695287611',
    projectId: 'mini-app-8f189',
    databaseURL: 'https://mini-app-8f189-default-rtdb.firebaseio.com',
    storageBucket: 'mini-app-8f189.appspot.com',
    androidClientId: '73695287611-o9c5ku12grh53d88cj304grv2d0c9m0a.apps.googleusercontent.com',
    iosClientId: '73695287611-ep6r5j2nvdhl4bv4cqrdasqtjhqmg3m3.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniApp',
  );
}
